require("core.mason-path")
require("core.lsp")
require("config.options")
require("config.keymaps")
require("config.mason-verify")
require("config.health-check")
require("config.commands")
require("core.lazy")
